version: '2.1'

services:

  nginx:
    build: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - dockerlocal

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
    networks:
      - dockerlocal
    environment:
      PHP_IDE_CONFIG: "serverName=ivisa"

  mysql:
    image: mysql:5.6
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ivisa
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - dockerlocal

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8880:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dockerlocal

networks:
  dockerlocal:
    driver: "bridge"

volumes:
  mysqldata:
    driver: "local"
